### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by dungeonsnd** [wonder-mice/zf_log#2]
Hey, man
I have some questions about zf_log.

1)  Is it support rolling ?   e.g. RollingFileAppender or DailyRollingFileAppender .
2)  I'm going to port zf_log to iOS and Android platforms, have you tested on these platforms yet? And do you have some scripts to build zf_log on these platforms ?
Thank you.

**Comment by wonder-mice** [comment]
Hi, thanks for your interest in zf_log.

> 1) Is it support rolling ? e.g. RollingFileAppender or DailyRollingFileAppender.
Currently no. Mostly because log file rotation could be implemented very differently, depending on tradeoffs you'd like to take. But it's very easy to write your own custom log callback function and use it with zf_log. Though, I'm thinking about having a zf_log_util library with commonly used "sinks".

> 2) I'm going to port zf_log to iOS and Android platforms, have you tested on these platforms yet?
zf_log has support for iOS and Android and was tested to work on them. You can use the same CMakeLists.txt script to build it or just grab zf_log.h and zf_log.cpp and integrate them into what ever build system you are currently using. Read firs part of zf_log.cpp, it will tell how to enable NSLog support on iOS and how to enable android_log support on Android.
