### ISSUE TITLE
asynchronous logging supported?

### ISSUE THREAD

**Issue by KaneFu** [wonder-mice/zf_log#22]
sorry to bother, but will zf_log support async logging?

**Comment by wonder-mice** [comment]
It already does. Library itself is thread safe, as well as default/bundled output callback functions. If you will write your own output callback function, then it's up to you to make it thread safe.

**Comment by KaneFu** [comment]
Really thanks.  Since I'm new to C++, also intern, my boss is interested in zf_log other than spdlog being used now).  Much to explore

**Comment by wonder-mice** [comment]
I would advice agains header-only libraries. They (usually) blow executable size and (almost always) increase compilation times, especially if they are template-heavy. However, spdlog offers nicer formatters via `fmt` library, but also pays performance price for using it.

**Comment by KaneFu** [comment]
Really sorry to bother again, but I didn't see any async-like API in "zf_log.h",  so to implement async logging,  I write customized callback function to output to a buffer, then create another thread to log this buffer like spdlog?  Shall I do this myself or is there any api like spdlog::set async_mode() ?

**Comment by wonder-mice** [comment]
That depends. What your use case is and why you think you need "async" logging? Modern (read all) operating systems already have buffers for IO and they don't do IO synchronously. You will block on IO only when you provide data faster then OS can write this data to file (or send over network). You will have exactly the same problem with any async logging - if you produce faster then it can be consumed, you either will need to block eventually (or increase buffer size indefinitely) or drop some of log messages.

First, you need to decide why you need async logging in a first place. In most cases, using zf_log's (thread safe) implementation provides excellent performance. Measure first, and only if logging is really a bottle net, try to do something about it. If logging is a bottle net, I would say it's a higher level problem on your side. Maybe you shouldn't log that much? Tons of junk logs are not valuably to anybody. Or maybe instead of text base logging, you need to use binary output format, which will be much more compact and requires less overhead to produce (string formatting routines are slow).

There are cases when logging with faster than IO performance is necessary. However, such cases are relatively rare and usually there are better solutions available. Not always though. If your use case is so special, than yes, you will need to write custom callback function that does what you want. But measure first, chances are that your custom implementation will not be better than default one.

**Comment by KaneFu** [comment]
thanks for being a patient and nice uploader!  I did some tests on spdlog async v.s zflog sync.  50w logs(40Mb), zflog is even faster than the time spdlog write to buffer quene. I will dig into more why zf_log is thread safe

**Comment by wonder-mice** [comment]
zf_log itself is thread safe because there is no shared data between threads. Each thread is independent and doesn't need any synchronization with other threads (as far as zf_log implementation is concerned). Default output callback is thread safe because it just directly calls one of system functions that are also thread safe.

Currently though, there is no default implementation for file output callback, but it's trivial to build one.

**Comment by wonder-mice** [comment]
Also

>  zflog is even faster than the time spdlog write to buffer quene

This is surprising to me, I would double check your test setup that they are correct and that you measuring something that is relevant to your use case.
