### ISSUE TITLE
Add a possibility to use external snprintf function

### ISSUE THREAD

**Issue by mgiaco** [wonder-mice/zf_log#27]
Hi,

Do you see any possibility to use some external vsnprintf? I would like to use zf_log in comination with https://github.com/mpaland/printf which is a nice printf / snprintf implementation. So therefore i want that zf_log uses snprintf instead of the vsnprintf.

With the current implementation this is not possible. Can you add any way to change it. I can also add a pull if you can give me a hint how you would like to solve it that i will go main line.

many thanks
cheers
mathias

**Comment by mgiaco** [comment]
Hm I do not exactly understand what you mean. For something like this would be fine.

```C
#ifndef ZF_LOG_SNPRINTF
#define ZF_LOG_SNPRINTF vsnprintf
#endif
```

Then I can define my own

```C
#define ZF_LOG_SNPRINTF my_snprintf
```

Minimal an easy change or do you think that is dangerous?

**Comment by wonder-mice** [comment]
Well, you'll need to provide a declaration for `my_snprintf()` function as well. Otherwise, compiler will not know what it is. Though we probably can just cast it to predefined function type and `my_snprintf` will just need to conform. I agree, that's a simpler and better solution. Go ahead and make it work for you and then we can see the patch.

**Comment by mgiaco** [comment]
Yes I know that´s not the problem. 
Okay many thanks I will add a pull.

**Comment by wonder-mice** [comment]
Done in 4f40333.
